### ISSUE TITLE
Gostei muito :+1:

### ISSUE THREAD

**Issue by Mxrcon** [erickeloi/Bot-Ferias-UFPA#1]
Gostei muito desse projeto, a estrutura do projeto está excelente, belo trabalho :+1:
Se você precisar de algo me avise, gostaria muito de contribuir com o trabalho, eu achei bem divertido.

Sucesso pra vocês! :rocket:

**Comment by erickeloi** [comment]
Muito Obrigado pelo cumprimento e Elogio!!!

Atualmente o projeto ainda é bem embrionário, atualmente é necessário executá-lo uma vez por dia para ele postar o Tweet do dia.

Queremos achar meios de hospeda-lo em um servidor para não ser necessário usar nossos computadores com agendador de tarefa para executar o programa diariamente.

Além de futuramente refinar o projeto para algo mais escalável, como uma API/Site ou algo nesse sentido.

Meu discord é: 
Paiaço#2920 

Pode adicionar lá, vamos trocar umas figurinhas! 
E uma ajuda no projeto é bem vinda!!!

**Comment by Mxrcon** [comment]
Beleza, vou enviar uma mensagem! Eu ja hospedei um bot em python p telegram no Heroku, Não é tão dificil quanto parece, acho que é bem facil de manter esse projeto lá já que só é necessário uma execução por dia!
